### PR TITLE
Add support for Perl 5.5.x versions

### PR DESCRIPTION
**Pull request by pali**
Travis tests with 5.5.3 version passes with changes in these pull requests:
https://github.com/travis-perl/TravisCI-Helpers-InstallerTest/pull/1
https://github.com/travis-perl/TravisCI-Helpers-InstallerTest/pull/2

### CODE REVIEW

**Comment by karenetheridge** [comment]
This is being used for Devel-PPPort -- https://github.com/Dual-Life/Devel-PPPort/pull/104

**Comment by pali** [comment]
@haarg can you look at this PR?

**Comment by pali** [comment]
@haarg ping

**Comment by pali** [comment]
@haarg Could you please look at this pull request? We need it for Devel::PPPort testing.

**Comment by pali** [comment]
@haarg ping

**Pull request merged**
