### PR TITLE
Add a --travis-cache option that causes cpanm to be run without --skip-satisfied

### PR DESCRIPTION
**Pull request by autarch**
I'm not really set on this particular argument name or this implementation, but it does seem to work. See https://travis-ci.org/autarch/Specio/builds/136857643 for a build where this flag was passed.

### CODE REVIEW

**Comment by autarch** [comment]
Ping ...

**Comment by haarg** [comment]
For cpan-install, the option should be something more like --update-prereqs.  I'd kind of rather have the options in general based on what they do rather than how they may be used.  --travis-cache might be fine for the init option.  I can't really think of a much better option.

**Comment by autarch** [comment]
I updated this to change the option name in `cpan-install`

**Comment by autarch** [comment]
Ping ... I'd love to get this going to speed up my many many many Travis builds ;)

**Comment by autarch** [comment]
Ping.

**Comment by leto** [comment]
:+1: to this PR. I just tried to use the new option and realized the PR hadn't been merged yet

**Comment by haarg** [comment]
Merged as 530b6e793f279931ee358cdf71c07dbabce29306

**Pull request closed without merging**
